const canvas=document.getElementById('table');const ctx=canvas.getContext('2d');const power=document.getElementById('power');const powerValue=document.getElementById('powerValue');const scoreEl=document.getElementById('score');const bestEl=document.getElementById('bestBreak');const statusEl=document.getElementById('statusText');const shotsEl=document.getElementById('shotCount');
const W=1200,H=660,table={x:74,y:62,w:1052,h:536,r:30},pocketR=24,ballR=11;let balls=[],aim={x:520,y:330},isMoving=false,score=0,best=Number(localStorage.getItem('breakline-best')||0),shots=0;bestEl.textContent=best;
const colors={red:'#c94742',yellow:'#d4b93b',green:'#4c8055',brown:'#8a6146',blue:'#447fae',pink:'#d6839a',black:'#252a27',white:'#f2efe5'};const values={red:1,yellow:2,green:3,brown:4,blue:5,pink:6,black:7};
function reset(){balls=[];score=0;shots=0;isMoving=false;addBall('white',table.x+table.w*.28,table.y+table.h*.5);const startX=table.x+table.w*.72,startY=table.y+table.h*.5;let reds=0;for(let row=0;row<5;row++)for(let col=0;col<=row;col++){addBall('red',startX+row*22,startY+(col-row/2)*23);reds++}addBall('yellow',table.x+table.w*.2,table.y+table.h*.78);addBall('green',table.x+table.w*.2,table.y+table.h*.22);addBall('brown',table.x+table.w*.2,table.y+table.h*.5);addBall('blue',table.x+table.w*.5,table.y+table.h*.5);addBall('pink',startX-40,startY);addBall('black',table.x+table.w*.87,startY);updateHud();statusEl.textContent='Aim with your mouse'}
function addBall(type,x,y){balls.push({type,x,y,vx:0,vy:0,alive:true})}function cue(){return balls.find(b=>b.type==='white'&&b.alive)}function updateHud(){scoreEl.textContent=score;shotsEl.textContent=`${shots} ${shots===1?'shot':'shots'}`;bestEl.textContent=best;powerValue.textContent=`${power.value}%`}
function resize(){const rect=canvas.getBoundingClientRect();const dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0)}
function pointer(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}}
canvas.addEventListener('pointermove',e=>{aim=pointer(e)});canvas.addEventListener('pointerdown',e=>{if(isMoving)return;const p=pointer(e),c=cue();if(!c)return;const dx=c.x-p.x,dy=c.y-p.y,dist=Math.hypot(dx,dy);if(dist<25){statusEl.textContent='Point away from the cue ball to aim';return}const force=Number(power.value)/100*8.4;c.vx=dx/dist*force;c.vy=dy/dist*force;isMoving=true;shots++;statusEl.textContent='Stroke in play';updateHud()});power.addEventListener('input',updateHud);document.getElementById('newFrame').addEventListener('click',reset);window.addEventListener('resize',resize);
function pocketCheck(b){const pockets=[[table.x,table.y],[table.x+table.w/2,table.y-4],[table.x+table.w,table.y],[table.x,table.y+table.h],[table.x+table.w/2,table.y+table.h+4],[table.x+table.w,table.y+table.h]];for(const [px,py] of pockets)if(Math.hypot(b.x-px,b.y-py)<pocketR){b.alive=false;b.vx=b.vy=0;if(b.type!=='white'){score+=values[b.type];if(score>best){best=score;localStorage.setItem('breakline-best',best)}}else{setTimeout(()=>{if(!cue())addBall('white',table.x+table.w*.28,table.y+table.h*.5)},650)}updateHud();return true}return false}
function step(){let active=false;for(const b of balls){if(!b.alive)continue;b.x+=b.vx;b.y+=b.vy;b.vx*=.986;b.vy*=.986;if(Math.abs(b.vx)+Math.abs(b.vy)>.018)active=true;if(pocketCheck(b))continue;const left=table.x+ballR,right=table.x+table.w-ballR,top=table.y+ballR,bottom=table.y+table.h-ballR;if(b.x<left){b.x=left;b.vx=Math.abs(b.vx)*.92}if(b.x>right){b.x=right;b.vx=-Math.abs(b.vx)*.92}if(b.y<top){b.y=top;b.vy=Math.abs(b.vy)*.92}if(b.y>bottom){b.y=bottom;b.vy=-Math.abs(b.vy)*.92}}
for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(!a.alive||!b.alive)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=ballR*2;if(d&&d<min){const nx=dx/d,ny=dy/d,over=(min-d)/2;a.x-=nx*over;a.y-=ny*over;b.x+=nx*over;b.y+=ny*over;const av=a.vx*nx+a.vy*ny,bv=b.vx*nx+b.vy*ny;const impulse=bv-av;a.vx+=impulse*nx;a.vy+=impulse*ny;b.vx-=impulse*nx;b.vy-=impulse*ny}}
if(isMoving&&!active){isMoving=false;statusEl.textContent='Aim with your mouse'}return active}
function draw(){ctx.clearRect(0,0,W,H);drawTable();for(const b of balls)if(b.alive)drawBall(b);if(!isMoving&&cue())drawAim();requestAnimationFrame(()=>{step();draw()})}
function drawTable(){ctx.fillStyle='#0d1c17';ctx.fillRect(0,0,W,H);ctx.save();ctx.shadowColor='rgba(0,0,0,.5)';ctx.shadowBlur=24;ctx.fillStyle='#a78a60';roundRect(table.x-26,table.y-26,table.w+52,table.h+52,18);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#0b251b';roundRect(table.x,table.y,table.w,table.h,table.r);ctx.fill();ctx.strokeStyle='rgba(165,204,151,.26)';ctx.lineWidth=2;roundRect(table.x+16,table.y+16,table.w-32,table.h-32,20);ctx.stroke();const ps=[[table.x,table.y],[table.x+table.w/2,table.y-4],[table.x+table.w,table.y],[table.x,table.y+table.h],[table.x+table.w/2,table.y+table.h+4],[table.x+table.w,table.y+table.h]];for(const [x,y]of ps){ctx.beginPath();ctx.fillStyle='#101611';ctx.arc(x,y,pocketR,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.strokeStyle='rgba(220,194,136,.35)';ctx.lineWidth=2;ctx.arc(x,y,pocketR+5,0,Math.PI*2);ctx.stroke()}ctx.strokeStyle='rgba(207,187,130,.25)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(table.x+table.w*.2,table.y+14);ctx.lineTo(table.x+table.w*.2,table.y+table.h-14);ctx.stroke();ctx.beginPath();ctx.arc(table.x+table.w*.2,table.y+table.h*.5,70,-Math.PI/2,Math.PI/2);ctx.stroke();ctx.restore()}
function drawBall(b){ctx.save();ctx.shadowColor='rgba(0,0,0,.48)';ctx.shadowBlur=7;ctx.shadowOffsetY=3;ctx.beginPath();ctx.fillStyle=colors[b.type];ctx.arc(b.x,b.y,ballR,0,Math.PI*2);ctx.fill();ctx.shadowColor='transparent';ctx.beginPath();ctx.fillStyle='rgba(255,255,255,.36)';ctx.arc(b.x-3,b.y-3,2.4,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawAim(){const c=cue();const dx=c.x-aim.x,dy=c.y-aim.y,d=Math.hypot(dx,dy);if(!d)return;const nx=dx/d,ny=dy/d;ctx.save();ctx.setLineDash([10,9]);ctx.strokeStyle='rgba(239,217,157,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(c.x+nx*13,c.y+ny*13);ctx.lineTo(c.x+nx*(390+Number(power.value)*1.6),c.y+ny*(390+Number(power.value)*1.6));ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='rgba(255,255,255,.2)';ctx.beginPath();ctx.moveTo(c.x-nx*20,c.y-ny*20);ctx.lineTo(c.x-nx*(65+Number(power.value)*.7),c.y-ny*(65+Number(power.value)*.7));ctx.stroke();ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
reset();resize();draw();
